// <auto-generated />
using System;
using CourseManagementAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseManagementAPI.Migrations
{
    [DbContext(typeof(CourseManagementDbContext))]
    [Migration("20260511114827_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseManagementAPI.Models.Assessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assessmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentId"));

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int")
                        .HasColumnName("enrollmentID");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("instructorID");

                    b.Property<int?>("Result")
                        .HasColumnType("int")
                        .HasColumnName("result");

                    b.Property<int?>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.HasKey("AssessmentId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Assessment", (string)null);

                    b.HasData(
                        new
                        {
                            AssessmentId = 1,
                            EnrollmentId = 1,
                            InstructorId = 1,
                            Result = 1,
                            Score = 85
                        });
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Certification", b =>
                {
                    b.Property<int>("CertificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("certificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificationId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("CertificationId");

                    b.ToTable("Certification", (string)null);

                    b.HasData(
                        new
                        {
                            CertificationId = 1,
                            Description = "Certificate for web development skills",
                            Name = "Web Development Certificate"
                        },
                        new
                        {
                            CertificationId = 2,
                            Description = "Certificate for database basics",
                            Name = "Database Fundamentals Certificate"
                        });
                });

            modelBuilder.Entity("CourseManagementAPI.Models.CertificationCourse", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("courseID");

                    b.Property<int>("CertificationId")
                        .HasColumnType("int")
                        .HasColumnName("certificationID");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit")
                        .HasColumnName("isRequired");

                    b.HasKey("CourseId", "CertificationId");

                    b.HasIndex("CertificationId");

                    b.ToTable("CertificationCourse", (string)null);

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CertificationId = 1,
                            IsRequired = true
                        },
                        new
                        {
                            CourseId = 2,
                            CertificationId = 2,
                            IsRequired = true
                        });
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Classroom", b =>
                {
                    b.Property<int>("ClassroomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("classroomID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassroomId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location");

                    b.HasKey("ClassroomId");

                    b.ToTable("Classroom", (string)null);

                    b.HasData(
                        new
                        {
                            ClassroomId = 1,
                            Capacity = 25,
                            IsActive = true,
                            Location = "Room A101"
                        },
                        new
                        {
                            ClassroomId = 2,
                            Capacity = 30,
                            IsActive = true,
                            Location = "Room B202"
                        });
                });

            modelBuilder.Entity("CourseManagementAPI.Models.ClassroomEquipment", b =>
                {
                    b.Property<int>("ClassroomId")
                        .HasColumnType("int")
                        .HasColumnName("classroomID");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("equipmentID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("ClassroomId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("ClassroomEquipment", (string)null);

                    b.HasData(
                        new
                        {
                            ClassroomId = 1,
                            EquipmentId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            ClassroomId = 1,
                            EquipmentId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            ClassroomId = 2,
                            EquipmentId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            ClassroomId = 2,
                            EquipmentId = 2,
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("courseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryID");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("courseCode");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("courseName");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<decimal>("EnrollmentFee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("enrollmentFee");

                    b.HasKey("CourseId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Course", (string)null);

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Capacity = 20,
                            CategoryId = 1,
                            CourseCode = "WEB101",
                            CourseName = "Introduction to Web Development",
                            Description = "HTML, CSS, and JavaScript basics",
                            EnrollmentFee = 120m
                        },
                        new
                        {
                            CourseId = 2,
                            Capacity = 25,
                            CategoryId = 3,
                            CourseCode = "DB101",
                            CourseName = "Database Fundamentals",
                            Description = "Introduction to relational databases",
                            EnrollmentFee = 100m
                        });
                });

            modelBuilder.Entity("CourseManagementAPI.Models.CourseCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("categoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("categoryName");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.HasKey("CategoryId");

                    b.ToTable("CourseCategory", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Programming",
                            Description = "Software and coding courses"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Networking",
                            Description = "Network and infrastructure courses"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Database",
                            Description = "Database management courses"
                        });
                });

            modelBuilder.Entity("CourseManagementAPI.Models.CoursePrerequisite", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("courseID");

                    b.Property<int>("CoursePrerequisiteId")
                        .HasColumnType("int")
                        .HasColumnName("coursePrerequisiteID");

                    b.HasKey("CourseId", "CoursePrerequisiteId");

                    b.HasIndex("CoursePrerequisiteId");

                    b.ToTable("CoursePrerequisite", (string)null);

                    b.HasData(
                        new
                        {
                            CourseId = 2,
                            CoursePrerequisiteId = 1
                        });
                });

            modelBuilder.Entity("CourseManagementAPI.Models.CourseReqEquipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("equipmentID");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("courseID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("EquipmentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseReqEquipment", (string)null);

                    b.HasData(
                        new
                        {
                            EquipmentId = 2,
                            CourseId = 1,
                            Quantity = 10
                        },
                        new
                        {
                            EquipmentId = 2,
                            CourseId = 2,
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("CourseManagementAPI.Models.CourseSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sessionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int")
                        .HasColumnName("classroomID");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("courseID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("endDateTime");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("instructorID");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("startDateTime");

                    b.HasKey("SessionId");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("CourseSession", (string)null);

                    b.HasData(
                        new
                        {
                            SessionId = 1,
                            Capacity = 20,
                            ClassroomId = 1,
                            CourseId = 1,
                            CreatedAt = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateTime = new DateTime(2026, 6, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 1,
                            StartDateTime = new DateTime(2026, 6, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SessionId = 2,
                            Capacity = 25,
                            ClassroomId = 2,
                            CourseId = 2,
                            CreatedAt = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateTime = new DateTime(2026, 6, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 2,
                            StartDateTime = new DateTime(2026, 6, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("enrollmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<DateOnly>("EnrollmentDate")
                        .HasColumnType("date")
                        .HasColumnName("enrollmentDate");

                    b.Property<int>("EnrollmentStatusId")
                        .HasColumnType("int")
                        .HasColumnName("enrollmentStatusID");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("sessionID");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int")
                        .HasColumnName("traineeID");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("EnrollmentStatusId");

                    b.HasIndex("SessionId");

                    b.HasIndex("TraineeId");

                    b.ToTable("Enrollment", (string)null);

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            EnrollmentDate = new DateOnly(2026, 5, 5),
                            EnrollmentStatusId = 2,
                            SessionId = 1,
                            TraineeId = 1
                        },
                        new
                        {
                            EnrollmentId = 2,
                            EnrollmentDate = new DateOnly(2026, 5, 6),
                            EnrollmentStatusId = 1,
                            SessionId = 2,
                            TraineeId = 2
                        });
                });

            modelBuilder.Entity("CourseManagementAPI.Models.EnrollmentStatus", b =>
                {
                    b.Property<int>("EnrollmentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("enrollmentStatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentStatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("statusName");

                    b.HasKey("EnrollmentStatusId");

                    b.ToTable("EnrollmentStatus", (string)null);

                    b.HasData(
                        new
                        {
                            EnrollmentStatusId = 1,
                            StatusName = "Pending"
                        },
                        new
                        {
                            EnrollmentStatusId = 2,
                            StatusName = "Enrolled"
                        },
                        new
                        {
                            EnrollmentStatusId = 3,
                            StatusName = "Completed"
                        },
                        new
                        {
                            EnrollmentStatusId = 4,
                            StatusName = "Cancelled"
                        });
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("equipmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("equipmentName");

                    b.HasKey("EquipmentId");

                    b.ToTable("Equipment", (string)null);

                    b.HasData(
                        new
                        {
                            EquipmentId = 1,
                            Description = "Classroom projector",
                            EquipmentName = "Projector"
                        },
                        new
                        {
                            EquipmentId = 2,
                            Description = "Training laptop",
                            EquipmentName = "Laptop"
                        },
                        new
                        {
                            EquipmentId = 3,
                            Description = "Classroom whiteboard",
                            EquipmentName = "Whiteboard"
                        });
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("instructorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fullName");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("hireDate");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("Qualifications")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("qualifications");

                    b.HasKey("InstructorId");

                    b.ToTable("Instructor", (string)null);

                    b.HasData(
                        new
                        {
                            InstructorId = 1,
                            Email = "ahmed.ali@example.com",
                            FullName = "Ahmed Ali",
                            HireDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "Temp123",
                            Phone = "+97333112244",
                            Qualifications = "MSc Computer Science"
                        },
                        new
                        {
                            InstructorId = 2,
                            Email = "sara.hassan@example.com",
                            FullName = "Sara Hassan",
                            HireDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "Temp123",
                            Phone = "+97333225566",
                            Qualifications = "BSc Information Technology"
                        });
                });

            modelBuilder.Entity("CourseManagementAPI.Models.InstructorAvailability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("availabilityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailabilityId"));

                    b.Property<DateOnly>("AvailableDate")
                        .HasColumnType("date")
                        .HasColumnName("availableDate");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("endTime");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("instructorID");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit")
                        .HasColumnName("isAvailable");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("startTime");

                    b.HasKey("AvailabilityId");

                    b.HasIndex("InstructorId");

                    b.ToTable("InstructorAvailability", (string)null);

                    b.HasData(
                        new
                        {
                            AvailabilityId = 1,
                            AvailableDate = new DateOnly(2026, 6, 1),
                            EndTime = new TimeOnly(14, 0, 0),
                            InstructorId = 1,
                            IsAvailable = true,
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            AvailabilityId = 2,
                            AvailableDate = new DateOnly(2026, 6, 2),
                            EndTime = new TimeOnly(14, 0, 0),
                            InstructorId = 2,
                            IsAvailable = true,
                            StartTime = new TimeOnly(8, 0, 0)
                        });
                });

            modelBuilder.Entity("CourseManagementAPI.Models.InstructorExpertise", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryID");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("instructorID");

                    b.HasKey("CategoryId", "InstructorId");

                    b.HasIndex("InstructorId");

                    b.ToTable("InstructorExpertise", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            InstructorId = 1
                        },
                        new
                        {
                            CategoryId = 3,
                            InstructorId = 2
                        });
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("paymentID");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("sessionID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("NotificationId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("SessionId");

                    b.ToTable("Notification", (string)null);

                    b.HasData(
                        new
                        {
                            NotificationId = 1,
                            Message = "Your payment has been received.",
                            PaymentId = 1,
                            Title = "Payment Received"
                        },
                        new
                        {
                            NotificationId = 2,
                            Message = "Your course session starts soon.",
                            SessionId = 1,
                            Title = "Session Reminder"
                        });
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("paymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amountPaid");

                    b.Property<decimal?>("BalanceRemaining")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balanceRemaining");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int")
                        .HasColumnName("enrollmentID");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("paymentDate");

                    b.Property<int>("PaymentStatusId")
                        .HasColumnType("int")
                        .HasColumnName("paymentStatusID");

                    b.HasKey("PaymentId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("PaymentStatusId");

                    b.ToTable("Payment", (string)null);

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            AmountPaid = 120m,
                            BalanceRemaining = 0m,
                            EnrollmentId = 1,
                            PaymentDate = new DateOnly(2026, 5, 6),
                            PaymentStatusId = 2
                        },
                        new
                        {
                            PaymentId = 2,
                            AmountPaid = 50m,
                            BalanceRemaining = 50m,
                            EnrollmentId = 2,
                            PaymentDate = new DateOnly(2026, 5, 7),
                            PaymentStatusId = 3
                        });
                });

            modelBuilder.Entity("CourseManagementAPI.Models.PaymentStatus", b =>
                {
                    b.Property<int>("PaymentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("paymentStatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentStatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("statusName");

                    b.HasKey("PaymentStatusId");

                    b.ToTable("PaymentStatus", (string)null);

                    b.HasData(
                        new
                        {
                            PaymentStatusId = 1,
                            StatusName = "Pending"
                        },
                        new
                        {
                            PaymentStatusId = 2,
                            StatusName = "Paid"
                        },
                        new
                        {
                            PaymentStatusId = 3,
                            StatusName = "Partially Paid"
                        },
                        new
                        {
                            PaymentStatusId = 4,
                            StatusName = "Unpaid"
                        });
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Trainee", b =>
                {
                    b.Property<int>("TraineeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("traineeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TraineeId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fullName");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("organizationName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date")
                        .HasColumnName("registrationDate");

                    b.Property<int>("TraineeStatusId")
                        .HasColumnType("int")
                        .HasColumnName("traineeStatusID");

                    b.HasKey("TraineeId");

                    b.HasIndex("TraineeStatusId");

                    b.ToTable("Trainee", (string)null);

                    b.HasData(
                        new
                        {
                            TraineeId = 1,
                            Email = "noor@example.com",
                            FullName = "Noor Mohammed",
                            OrganizationName = "ABC Company",
                            Password = "Temp123",
                            Phone = "+97339998877",
                            RegistrationDate = new DateOnly(2026, 5, 1),
                            TraineeStatusId = 1
                        },
                        new
                        {
                            TraineeId = 2,
                            Email = "ali@example.com",
                            FullName = "Ali Yusuf",
                            Password = "Temp123",
                            Phone = "+97338887766",
                            RegistrationDate = new DateOnly(2026, 5, 2),
                            TraineeStatusId = 1
                        });
                });

            modelBuilder.Entity("CourseManagementAPI.Models.TraineeCertificationProgress", b =>
                {
                    b.Property<int>("TraineeId")
                        .HasColumnType("int")
                        .HasColumnName("traineeID");

                    b.Property<int>("CertificationId")
                        .HasColumnType("int")
                        .HasColumnName("certificationID");

                    b.Property<DateOnly?>("AchievedDate")
                        .HasColumnType("date")
                        .HasColumnName("achievedDate");

                    b.Property<decimal>("ProgressPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("progressPercentage");

                    b.HasKey("TraineeId", "CertificationId");

                    b.HasIndex("CertificationId");

                    b.ToTable("TraineeCertificationProgress", (string)null);

                    b.HasData(
                        new
                        {
                            TraineeId = 1,
                            CertificationId = 1,
                            ProgressPercentage = 50m
                        });
                });

            modelBuilder.Entity("CourseManagementAPI.Models.TraineeStatus", b =>
                {
                    b.Property<int>("TraineeStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("traineeStatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TraineeStatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("statusName");

                    b.HasKey("TraineeStatusId");

                    b.ToTable("TraineeStatus", (string)null);

                    b.HasData(
                        new
                        {
                            TraineeStatusId = 1,
                            StatusName = "Active"
                        },
                        new
                        {
                            TraineeStatusId = 2,
                            StatusName = "Inactive"
                        });
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Assessment", b =>
                {
                    b.HasOne("CourseManagementAPI.Models.Enrollment", "Enrollment")
                        .WithMany("Assessments")
                        .HasForeignKey("EnrollmentId")
                        .IsRequired();

                    b.HasOne("CourseManagementAPI.Models.Instructor", "Instructor")
                        .WithMany("Assessments")
                        .HasForeignKey("InstructorId")
                        .IsRequired();

                    b.Navigation("Enrollment");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.CertificationCourse", b =>
                {
                    b.HasOne("CourseManagementAPI.Models.Certification", "Certification")
                        .WithMany("CertificationCourses")
                        .HasForeignKey("CertificationId")
                        .IsRequired();

                    b.HasOne("CourseManagementAPI.Models.Course", "Course")
                        .WithMany("CertificationCourses")
                        .HasForeignKey("CourseId")
                        .IsRequired();

                    b.Navigation("Certification");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.ClassroomEquipment", b =>
                {
                    b.HasOne("CourseManagementAPI.Models.Classroom", "Classroom")
                        .WithMany("ClassroomEquipments")
                        .HasForeignKey("ClassroomId")
                        .IsRequired();

                    b.HasOne("CourseManagementAPI.Models.Equipment", "Equipment")
                        .WithMany("ClassroomEquipments")
                        .HasForeignKey("EquipmentId")
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Course", b =>
                {
                    b.HasOne("CourseManagementAPI.Models.CourseCategory", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.CoursePrerequisite", b =>
                {
                    b.HasOne("CourseManagementAPI.Models.Course", "Course")
                        .WithMany("CoursePrerequisites")
                        .HasForeignKey("CourseId")
                        .IsRequired();

                    b.HasOne("CourseManagementAPI.Models.Course", "PrerequisiteCourse")
                        .WithMany("RequiredForCourses")
                        .HasForeignKey("CoursePrerequisiteId")
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("PrerequisiteCourse");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.CourseReqEquipment", b =>
                {
                    b.HasOne("CourseManagementAPI.Models.Course", "Course")
                        .WithMany("CourseReqEquipments")
                        .HasForeignKey("CourseId")
                        .IsRequired();

                    b.HasOne("CourseManagementAPI.Models.Equipment", "Equipment")
                        .WithMany("CourseReqEquipments")
                        .HasForeignKey("EquipmentId")
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.CourseSession", b =>
                {
                    b.HasOne("CourseManagementAPI.Models.Classroom", "Classroom")
                        .WithMany("CourseSessions")
                        .HasForeignKey("ClassroomId")
                        .IsRequired();

                    b.HasOne("CourseManagementAPI.Models.Course", "Course")
                        .WithMany("CourseSessions")
                        .HasForeignKey("CourseId")
                        .IsRequired();

                    b.HasOne("CourseManagementAPI.Models.Instructor", "Instructor")
                        .WithMany("CourseSessions")
                        .HasForeignKey("InstructorId")
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Enrollment", b =>
                {
                    b.HasOne("CourseManagementAPI.Models.EnrollmentStatus", "EnrollmentStatus")
                        .WithMany("Enrollments")
                        .HasForeignKey("EnrollmentStatusId")
                        .IsRequired();

                    b.HasOne("CourseManagementAPI.Models.CourseSession", "Session")
                        .WithMany("Enrollments")
                        .HasForeignKey("SessionId")
                        .IsRequired();

                    b.HasOne("CourseManagementAPI.Models.Trainee", "Trainee")
                        .WithMany("Enrollments")
                        .HasForeignKey("TraineeId")
                        .IsRequired();

                    b.Navigation("EnrollmentStatus");

                    b.Navigation("Session");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.InstructorAvailability", b =>
                {
                    b.HasOne("CourseManagementAPI.Models.Instructor", "Instructor")
                        .WithMany("InstructorAvailabilities")
                        .HasForeignKey("InstructorId")
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.InstructorExpertise", b =>
                {
                    b.HasOne("CourseManagementAPI.Models.CourseCategory", "Category")
                        .WithMany("InstructorExpertises")
                        .HasForeignKey("CategoryId")
                        .IsRequired();

                    b.HasOne("CourseManagementAPI.Models.Instructor", "Instructor")
                        .WithMany("InstructorExpertises")
                        .HasForeignKey("InstructorId")
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Notification", b =>
                {
                    b.HasOne("CourseManagementAPI.Models.Payment", "Payment")
                        .WithMany("Notifications")
                        .HasForeignKey("PaymentId");

                    b.HasOne("CourseManagementAPI.Models.CourseSession", "Session")
                        .WithMany("Notifications")
                        .HasForeignKey("SessionId");

                    b.Navigation("Payment");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Payment", b =>
                {
                    b.HasOne("CourseManagementAPI.Models.Enrollment", "Enrollment")
                        .WithMany("Payments")
                        .HasForeignKey("EnrollmentId")
                        .IsRequired();

                    b.HasOne("CourseManagementAPI.Models.PaymentStatus", "PaymentStatus")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentStatusId")
                        .IsRequired();

                    b.Navigation("Enrollment");

                    b.Navigation("PaymentStatus");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Trainee", b =>
                {
                    b.HasOne("CourseManagementAPI.Models.TraineeStatus", "TraineeStatus")
                        .WithMany("Trainees")
                        .HasForeignKey("TraineeStatusId")
                        .IsRequired();

                    b.Navigation("TraineeStatus");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.TraineeCertificationProgress", b =>
                {
                    b.HasOne("CourseManagementAPI.Models.Certification", "Certification")
                        .WithMany("TraineeCertificationProgresses")
                        .HasForeignKey("CertificationId")
                        .IsRequired();

                    b.HasOne("CourseManagementAPI.Models.Trainee", "Trainee")
                        .WithMany("TraineeCertificationProgresses")
                        .HasForeignKey("TraineeId")
                        .IsRequired();

                    b.Navigation("Certification");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Certification", b =>
                {
                    b.Navigation("CertificationCourses");

                    b.Navigation("TraineeCertificationProgresses");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Classroom", b =>
                {
                    b.Navigation("ClassroomEquipments");

                    b.Navigation("CourseSessions");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Course", b =>
                {
                    b.Navigation("CertificationCourses");

                    b.Navigation("CoursePrerequisites");

                    b.Navigation("CourseReqEquipments");

                    b.Navigation("CourseSessions");

                    b.Navigation("RequiredForCourses");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.CourseCategory", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("InstructorExpertises");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.CourseSession", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Enrollment", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.EnrollmentStatus", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Equipment", b =>
                {
                    b.Navigation("ClassroomEquipments");

                    b.Navigation("CourseReqEquipments");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Instructor", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("CourseSessions");

                    b.Navigation("InstructorAvailabilities");

                    b.Navigation("InstructorExpertises");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Payment", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.PaymentStatus", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.Trainee", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("TraineeCertificationProgresses");
                });

            modelBuilder.Entity("CourseManagementAPI.Models.TraineeStatus", b =>
                {
                    b.Navigation("Trainees");
                });
#pragma warning restore 612, 618
        }
    }
}
